project:
  type: website

website:
  title: "My Data Science Blog"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: posts/index.qmd
        text: Blog
      - href: about.qmd
        text: About
  site-url: "https://username.github.io/blog-name/"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
