project:
  type: website

website:
  title: "Learn Quarto"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: posts/index.qmd
        text: Blog
      - href: about.qmd
        text: About
  site-url: "https://adilsiraju.github.io/Quarto-Blog-Tutorial/"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
